name: Grow git-bonsai

on:
  push:
    branches:
      - main
    paths:
      - README.md
      - .github/workflows/bonsai.yml
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  grow:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: egorthinks/git-bonsai@v1
        with:
          user: munaabujaber
